version: '3'
services:
  nginx:
   container_name: spring-nginx
   image: nginx:1.14
   restart: always
   ports:
   - "8480:80"
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
  app:
    restart: always
    build: ./sbapp
    working_dir: /sbapp
    volumes:
      - ./sbapp:/sbapp
    expose:
      - "8480"
    command: mvn clean spring-boot:run
    depends_on:
      - nginx
